kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    meta.helm.sh/release-name: instana-agent
    meta.helm.sh/release-namespace: instana-agent
  resourceVersion: '272612687'
  name: instana-agent
  uid: b80a694c-24e2-42fd-862e-aadeca7e292d
  creationTimestamp: '2022-04-20T12:41:41Z'
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: v1
      time: '2022-04-30T23:32:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:cluster_name': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
            'f:helm.sh/chart': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"a981b095-246a-4210-8dfc-836e540499dd"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-05-10T14:28:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:configuration.yaml': {}
  namespace: instana-agent
  ownerReferences:
    - apiVersion: instana.io/v1
      kind: InstanaAgent
      name: instana-agent
      uid: a981b095-246a-4210-8dfc-836e540499dd
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/instance: instana-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: instana-agent
    app.kubernetes.io/version: 1.2.35
    helm.sh/chart: instana-agent-1.2.35
data:
  cluster_name: lgcluster-cp4i
  configuration.yaml: |
    com.instana.plugin.ibmmq:
      enabled: true
      poll_rate: 60
      queueManagers:
        qm1:
          channel: 'INSTANA.SVRCONN'
          port: '1414'
          queuesRegex: '^(?!SYSTEM|AMQ).*$' # Optional regex for filtering queues
          poll_rate: 60 
